### ISSUE TITLE
Linux - [ERR] Warning: Failed to find package 'system-images'

### ISSUE THREAD

**Issue by neoacevedo** [toroxx/vscode-avdmanager#1]
When I click in the image I want to download, the output shows the following:

> exec: /home/user/bin/android/sdk/cmdline-tools/latest/bin/sdkmanager system-images;android-30;google_apis;x86_64

As you see, the part after sdkmanager comes without quotes what raises the error in the title.

**Comment by toroxx** [comment]
I have reviewed all the commands and added quotes. 
Please update to the latest version  (v1.2.1).
