### ISSUE TITLE
Config Error SDK/AVD managers not found in cmdline-tools

### ISSUE THREAD

**Issue by jbtdevgit** [toroxx/vscode-avdmanager#11]
**Describe the Issue**
I tried setting up the environment variables and settings in the plugin, however, I am getting an error that the sdk and avd managers are not found. Shown below, the first image, shows the path of my cmd and open jdk.
![path_a](https://github.com/toroxx/vscode-avdmanager/assets/44351076/7a1685dd-ed0b-44df-b9fc-d750655fbab0)
![image](https://github.com/toroxx/vscode-avdmanager/assets/44351076/3fe34993-8374-4df6-9012-ed0e95268f80)

My .NET MAUI can detect the cmd-line tools so I am not sure about AVD Manager Plugin
![image](https://github.com/toroxx/vscode-avdmanager/assets/44351076/0f2c0b68-939e-4ce0-85a9-2c8e07d9f308)

**Expected behaviour**
Should detect the `.bat` files

**Screenshots and output logs**
```
Config Checking start 👓 ... 
SDK Root Path:            c:\Android-Sdk\sdk
SDK Command-Line Tools:   c:\Android-Sdk\sdk\cmdline-tools\c:\Android-Sdk\sdk\cmdline-tools\latest\bin
SDK Build Tools:          c:\Android-Sdk\sdk\build-tools
SDK Platform Tools:       c:\Android-Sdk\sdk\platform-tools
Emulator Path:            c:\Android-Sdk\sdk\emulator
 -- check OK 👍


AVD Manager path:         c:\Android-Sdk\sdk\cmdline-tools\latest\bin\avdmanager.bat
AVDManager path not specified / fail!😓
AVD Home path:            %ANDROID_EMULATOR_HOME%\avd\
SDK Manager path:         c:\Android-Sdk\sdk
SDKManager path not specified / fail!
Emulator path:            C:\Android-Sdk\sdk\emulator
Emulator path not specified / fail!😓
```

**Comment by toroxx** [comment]
avdmanager requires JDK8, please install and update `JAVA_HOME`

**Comment by jbtdevgit** [comment]
> avdmanager requires JDK8, please install and update `JAVA_HOME`

I updated the jdk and still have the same error.

**Comment by RollsChris** [comment]
Hey, im getting this error : 
<img width="1000" alt="image" src="https://github.com/toroxx/vscode-avdmanager/assets/6059035/cb94d2a6-cf75-4c70-b0b2-f6f08ff39d83">

I have this: 
	C:\Program Files\Android\jdk\jdk-8.0.302.8-hotspot
and
	C:\Program Files (x86)\Android\openjdk\jdk-17.0.8.101-hotspot

.net maui all seems fine and setup.

Is there anyway i can get this working or should i give up and just use vs?

thanks

**Comment by toroxx** [comment]
Try the below commands on your VSCode terminal to check JAVA exists.

```
java -version
```
Also those commands which is the tool used to check the avdmanager and sdkmanager are installed correctly.
Replace `<AVD Path>` to yours. E.g. C:\Program Files\Android\Sdk\cmdline-tools\latest

```
<AVD Path>/bin/avdmanager.bat list avd

<AVD Path>/bin/sdkmanager.bat --list_installed
```

**Comment by Letgamer** [comment]
Had the same issue, it did not work with JDK 8, but only with JDK 17

**Comment by toroxx** [comment]
I guess the new version of Android cmdline-tools had dropped the JAVA 8 support.
Thanks for your message @Letgamer and I had updated the documents.
