### ISSUE TITLE
I don't have the [+] button for creating a new AVD

### ISSUE THREAD

**Issue by atzorefFlutter** [toroxx/vscode-avdmanager#4]
Hi,
I don't have the [+] button for creating a new AVD, it has only a 'delete' button.

**Comment by toroxx** [comment]
The [+] button can find in the "SDK Platforms" as below images.
![image](https://user-images.githubusercontent.com/18657712/204096684-a311b741-de71-4ab9-b262-064a6811d2d2.png)

**Comment by toroxx** [comment]
This issue was closed because it has been inactive long time.

**Comment by julianfalcionelli** [comment]
I am having this problem, I don't have any '+' icon:

<img width="605" alt="Screenshot 2024-12-12 at 15 43 46" src="https://github.com/user-attachments/assets/506d23b6-93b0-43d5-897c-7021acb712a7" />

**Comment by toroxx** [comment]
Select one of the "system image". Create AVD need image not the sdk platform

**Comment by julianfalcionelli** [comment]
Gotcha, thanks @toroxx , for some reason I had just the SDK installed but without any System Images, so after installing any of them worked as expected.
