### ISSUE TITLE
Use ANDROID_HOME instead of ANDROID_SDK_ROOT

### ISSUE THREAD

**Issue by Singha360** [toroxx/vscode-avdmanager#5]
The official Android SDK documentation mentions that ANDROID_SDK_ROOT is deprecated and that ANDROID_HOME will replace it. Most CLI tool (Gradle, Bazel, etc) uses this new environment variable from what I am aware and this extension should reflect this new update.

[Here is the link where it mentions it](https://developer.android.com/tools/variables#envar)

I would suggest for backwards compatibility that we keep the old one and just append the new one inside the [code](https://github.com/toroxx/vscode-avdmanager/blob/e9c4666c2a93f35c7eab99f050246b8718126b5c/src/core.ts#L104).

Unless you would prefer to just use the new one.

Let me know what you think?

**Comment by toroxx** [comment]
Thanks for your comment. I would keep both in my tool.

The `ANDROID_HOME` support started in [v1.2.2](https://github.com/toroxx/vscode-avdmanager/blob/v1.2.2/src/core.ts#L106-L118).
