### ISSUE TITLE
 The path after avd is created is not the path I specified 

### ISSUE THREAD

**Issue by JokingAboutLife** [toroxx/vscode-avdmanager#6]
### The path after avd is created is not the path I specified ###
***Platform：Ubuntu 22.04.2 LTS***

I've set the relevant environment variables ( At last, `$USER` has replace my username ):
```
export ANDROID_HOME=/home/$USER/android/sdk
export ANDROID_AVD_HOME=/home/$USER/android/avd
export PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/emulator:${ANDROID_HOME}/platform-tools:$PATH
```

When I create an avd using with this plugin, the path is "~/.android/avd"
But When I create an avd using the "avdmanager" command in the ubuntu terminal, the path is specified by an environment variable ( /home/$USER/android/avd )

**Comment by toroxx** [comment]
You can check the AVD config in the output screen to confirm the SDK path settings.

Below is the sample in VSCode
![螢幕擷取畫面 2023-06-27 005231](https://github.com/toroxx/vscode-avdmanager/assets/18657712/748942cf-ab20-41b7-8b48-d327f60dea21)

**Comment by JokingAboutLife** [comment]
I've checked that the settings are no problem.
![image](https://github.com/toroxx/vscode-avdmanager/assets/46296997/c53854e3-bd69-4044-88f6-4b332c1eb6a1)

The path of the AVD created in the plugin is different from the path created in the terminal.
![image](https://github.com/toroxx/vscode-avdmanager/assets/46296997/59d039ec-e4f0-4a42-8712-90557e37ff20)

**Comment by toroxx** [comment]
Thanks for your message. I have updated the tools.
The `ANDROID_AVD_HOME` support started in [v1.3.0](https://github.com/toroxx/vscode-avdmanager/releases/tag/v1.3.0).

The new `AVD Home` can be set in User/Workspace settings. 
You can assign the AVD Home path (by project) without touching the `ANDROID_AVD_HOME`. 
![螢幕擷取畫面 2023-06-27 183701](https://github.com/toroxx/vscode-avdmanager/assets/18657712/096d2141-3b7d-4b07-a935-0685709a030c)
