### ISSUE TITLE
What is SDK manager? I tried every folder and .exe in my AndroidDev/SDK folder

### ISSUE THREAD

**Issue by Anonym0us33** [toroxx/vscode-avdmanager#8]
What is SDK manager? I tried every folder and .exe in my AndroidDev/SDK folder but it keeps pulling an error
https://docwiki.embarcadero.com/RADStudio/Sydney/en/SDK_Manager
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/2bb6f5b0-8144-4fc5-9e54-549737a1b866)

my emulator works fine in android studio but in vsc I have to use this tool and it's unclear what it wants me to point it to!
Could you please include a default path list and names of files it needs to be pointed to! Android studio only needs the root SDK path and it's fine!
It sees the VMs I made in AS but it cant start them!
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/1792acc0-14f8-4a24-b946-c05e1727c1cb)
```bash
ls
 analytics.settings   dirlist.txt   fonts                 platforms   system-images
 build-tools          emulator      licenses             patcher                              skins       tools
 cmdline-tools        extras        mklink-android.bat   platform-tools                       sources
```

**Comment by toroxx** [comment]
If you have follow the below. It should work correctly.
https://github.com/toroxx/vscode-avdmanager#setup-the-android-sdk

The `sdkmanager` is one for the tool inside the SDK cmdline-tools bin folder.
It helps the tools to look up which SDK package is installed in your system. 

Usually after setup the `avdmanager.sdkPath` or ANDROID_SDK_ROOT or ANDROID_HOME.
The AVDManager tools will help you find out everything. 
Except you have multiple sdk folders in your system.

You can check vscode output to find out which SDK is used (as below image).
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/1734c9f2-41b1-4712-a58b-9b2098ace99d)

**Comment by Anonym0us33** [comment]
my VSC doesnt show that screen with the thumbs up. it shows this
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/d48d505a-b4a8-4a85-96b2-d9171a6b66c9)

I want to know basically which path goes in each of these because of that.
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/979008a2-72e5-4551-813e-d7572be4dcb2)
Can you tell me what I need to do to show that screen these or which of the  2nd pic those paths correspond to? Am i meant to reference bin/sdkmanager.bat directly or just /bin?

**Comment by Anonym0us33** [comment]
oops wrong button

**Comment by Anonym0us33** [comment]
avd home= `\SDK`
cmd version = `\SDK\cmdline-tools\latest\bin`
emulator = `\SDK\tools\emulator.exe`
exe = `\SDK\tools\bin\avdmanager.bat`
sdk man = `\SDK\tools\bin\sdkmanager.bat`
sdk path = `SDK`

this is what i put  in under settings but i get this error (as above)
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/965876e0-ab61-481a-aebb-a2ed77161a6c)
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/d57bb2de-bdec-4565-9fb1-f98f3c9475aa)

**Comment by toroxx** [comment]
The `config path check` will show when your start the `AVDManager` in VSCode. 
if you don't see those messages in the `AVDManager` output panel.  
You can scroll it to the top. It will always show on the top. 

Your Android SDK may have some problems. The folders are unusual. 
Where did you download it? my guide or other places?

If your settings are correct. The emulator can be downloaded in the SDK tool panel. 
Try to download it and start the AVD.
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/50385b21-b3ac-464d-a359-8ba3b8407f92)

The `AVDManager` output messages will help solve the problems.
It will be more helpful if you show me more information.

**Comment by Anonym0us33** [comment]
I downloaded the SDK with android studio and moved it to another drive and reinstalled windows a few times. Then i put the `.android` folder inside it and simlinked it with `mklink` to the C:/users/username folder
for now i start it from cmd or from android studio but it's annoying having to open extra windows to run it so I downloaded this addon and into VSCodium IDE from the in-IDE store.
VSCodium is like a reskin for VSC that runs in portable mode that may or may not run without VSC installed.

**Comment by toroxx** [comment]
The tool should work on the VSCodium. Just have no idea why you need that tricky.
Are you going to share the same SDK folder with all your tools?

**Comment by Anonym0us33** [comment]
The point is to make the SDK standalone and usable across physical machines and OSs.
Are you able to share the expected settings for each of the paths so I can check if one is wrong? I suspect SDK/tools isn't the correct path to some of the executables for this job.

**Comment by toroxx** [comment]
Here is the easier way:

# Preparing the SDK

1. Assume that everything will place in the folder `C:\android-sdk`.  
Create folder `C:\android-sdk` and `C:\android-sdk\cmdline-tools`.
  ``` 
  mkdir C:\android-sdk
  mkdir C:\android-sdk\cmdline-tools
  ```

2. download the SDK command line tool (e.g. `commandlinetools-win-9477386_latest.zip`) from below link 
https://developer.android.com/studio#command-line-tools-only

3. open commandlinetools-win-9477386_latest.zip, you will see the `cmdline-tools`
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/92bf94c7-36e7-4a3c-80a2-06fc9b6efb8a)

4. unzip and rename the folder name from `cmdline-tools` to `latest`


5. move the `latest` to `C:\android-sdk\cmdline-tools`. 
The SDK folder will be like below
```
C:\android-sdk
└─cmdline-tools
    └─latest
        ├─lib
        └─bin
           ├─avdmanager.bat
           └─sdkmanager.bat
```

6. Set  the environment `ANDROID_HOME` to `C:\android-sdk`
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/7bcbc28e-f728-411f-aa98-13d96a9dba9e)


# Setup the VSCode and VSCode-like tools (E.g. VSCodium)
1. install AVD Manager
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/9f9b7883-ea8d-4281-8a97-d907eaa2de77)

2. Click the Android icon to open the AVD Manager
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/13ae121d-5e86-4281-a4b2-e248077e7f5b)

3. You may see below. Click `Download Emulator` to download the emulator
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/831b166f-6485-4662-9dc3-0de8f4f946f3)

4. If you click download. Wait until you see the `output` showing the download 100%.
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/8f284ec4-0e11-46ba-abbe-91c3288ef080)

5. restart your VSCode and open AVD manager

6. Complete
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/fc2e40e0-66d1-4db5-89d7-3aaaac1487ad)

# Setup Android Studio

1. Open the Android Studio, Click `More Actions`, `SDK Manager`
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/17fb4e98-9874-4c70-9df7-f2b1ddbf120a)

2. On `Android SDK Location‵, Click Edit
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/b372f901-db03-4eec-86ad-ad1de071f29f)

3. Change `Android SDK Location‵ to the SDK path (e.g. `C:\android-sdk`)
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/8c0ce221-2b48-4443-bc82-20990b01794e)

4. Click Next and complete the setup.
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/f1e79982-ed51-4186-ab74-f2a360ea8ce2)

-----
After all, the VSCode and Android Studio will share the same SDK tools.
Hope it helps.

**Comment by jcmljunior** [comment]
That didn't work out for me either.

https://github.com/toroxx/vscode-avdmanager/assets/82642883/16d02df3-a80f-4746-9ac7-e7e3b0f3c9e4

**Comment by Anonym0us33** [comment]
![259414646-831b166f-6485-4662-9dc3-0de8f4f946f3](https://github.com/toroxx/vscode-avdmanager/assets/128852225/e46c386a-65a4-4df8-9595-32cde9cfe876)
this image you shared is good, but can you share this image on your system? I have copied all the paths from this image into VSC but it still is not working.
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/e5d1fdd9-086b-4856-998f-9e2ca29cb43d)
Starting the emulator in AS works, and `flutter run -d <emulator name>` also works
All I did was redirect AS to the base SDK and localdata directory and it worked fine. Are you sure your addon doesn't have any hardcoded drive letters it is looking for? The SDK and .android directorys aren't on my C:/ drive as I mentioned...
Does this app depend on path variables being set in its own terminal? I could do something like 
`set ANDROID_HOME = D:/<path>/SDK`
but I'm not sure where `.android` comes in. But I can't see any reason linking it to the D: drive or symlinking it in C: shouldn't work...

**Comment by toroxx** [comment]
You can try the below commands on your VSCode.
Those commands which is the tool used to check the avdmanager and sdkmanager installed correctly. 
```
C:\android-sdk\cmdline-tools\latest\bin\avdmanager.bat list avd

C:\android-sdk\cmdline-tools\latest\bin\sdkmanager.bat --list_installed
```
You may see like below.
![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/b0cf5124-b98c-4289-b039-8878c7f59efc)

**Comment by toroxx** [comment]
Of course not. If hardcore other OS like Linux may not work
Here is the SDK on D drive 

![image](https://github.com/toroxx/vscode-avdmanager/assets/18657712/0e7ee05d-ed5c-4fcf-bec7-952916435f93)

**Comment by jcmljunior** [comment]
Hello, I found the solution to the problem.

1 - Download Java.
https://jdk.java.net/20/

2 - Set the environment variable.
JAVA_HOME=C:\Users\Julio\AppData\Local\Android\jdk-20.0.2

3 - Add the binaries under System Paths.
![image](https://github.com/toroxx/vscode-avdmanager/assets/82642883/defeece0-60d9-4120-9522-59de1e52d6ee)
![image](https://github.com/toroxx/vscode-avdmanager/assets/82642883/b6143822-9b1e-4d26-bdbf-c346f0914b6f)

**Comment by Anonym0us33** [comment]
I'm not sure if this is the issue, but i found this
```
java -version
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```
```
SDK\tools\bin\avdmanager.bat
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
...
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
```
here is me googling why this github can't start the AVD using my android virtual device I set up in android studio 20 minutes ago
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/b9e9705f-7559-4867-9e45-a007d5502f89)

I had to do this because my sanity demaded to know that it wasn't something wrong with my environment, which has been stable for almost a year now.

**Comment by Anonym0us33** [comment]
It was as we thought. There are 3 or 4 managers in my SDK. Maybe this is because different programs are using it like:
VSC
AS
quasar
flutter
```
\SDK\cmdline-tools\7.0\bin>avdmanager.bat  list avd
Available Android Virtual Devices:

The following Android Virtual Devices could not be loaded:
    Name: Pixel_6_Pro_API_33
\SDK\.android\avd\Pixel_6_Pro_API_33.avd
   Error: Google pixel_6_pro no longer exists as a device
```
```
\SDK\cmdline-tools\latest\bin>avdmanager.bat  list avd
Available Android Virtual Devices:
    Name: Pixel_6_Pro_API_33
  Device: pixel_6_pro (Google)
    Path: Z:\CREATIVITY_PROJECTS\VRNelectronics\AndroidDev\SDK\.android\avd\Pixel_6_Pro_API_33.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 13.0 (Tiramisu) Tag/ABI: google_apis/x86_64
    Skin: pixel_6_pro
  Sdcard: 512M
```
```
\SDK\tools\bin>avdmanager.bat  list avd
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
```
So for that I will use the second one.

**Comment by Anonym0us33** [comment]
what i dont understand is this popup
![image](https://github.com/toroxx/vscode-avdmanager/assets/128852225/012b5173-fdda-42c5-b8d6-8ad3d2a8c354)

which global does it mean?
